FROM openjdk:8
ADD target/Springboot-JAR-Docker-0.0.1-SNAPSHOT.jar Springboot-JAR-Docker-0.0.1-SNAPSHOT.jar 
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "Springboot-JAR-Docker-0.0.1-SNAPSHOT.jar"]
CMD ["start"]